DROP TABLE IF EXISTS student ;
CREATE TABLE student (
     id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
     name VARCHAR(100) NOT NULL COMMENT '수강생 이름',
     status VARCHAR(6) NULL COMMENT '수강생 상태'
);

DROP TABLE IF EXISTS enrollment;
CREATE TABLE enrollment (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    student_id BIGINT NOT NULL COMMENT '수강생 ID',
    course VARCHAR(100) NOT NULL COMMENT '수강과목',
    course_type VARCHAR(10) NOT NULL COMMENT '필수 여부'
);

DROP TABLE IF EXISTS score;
CREATE TABLE score (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
   student_id BIGINT NOT NULL COMMENT '수강생 ID',
   course VARCHAR(100) NOT NULL COMMENT '수강과목',
   round INT NOT NULL COMMENT '시험 회차',
   score INT(3) NOT NULL COMMENT '시험 점수'
);